/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterfacePanel4.java
 *
 * Created on 2009-05-05, 11:08:58
 */

package Interface; 

import GrafVisualization.Canvas1;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFrame;

/**
 *
 * @author zupa
 */
public class InterfacePanel4 extends javax.swing.JFrame {

    /** Tymczasowa tablica kosztów*/
    private int[][] koszty;

     private static final int INF=100000000;

     /**Ilość miast*/
    int ilosc;

    /** Creates new form InterfacePanel4 */
    public InterfacePanel4() {
        initComponents();
    }

    /**Trzeba dodać:
     * filtr typów
     * obsługę plików exelowych
     * sprawdzanie poprawności pliku
     * obsługę wyjątków
     */

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFileChooser1.setControlButtonsAreShown(false);
        jFileChooser1.setCurrentDirectory(null);
        jFileChooser1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Wczytaj z pliku", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 15))); // NOI18N

        jButton1.setText("Dalej");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Powrót");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int m1, m2, k;
        String linia;
        File plik = jFileChooser1.getSelectedFile();
        try{
             BufferedReader input =  new BufferedReader(new FileReader(plik));
             ilosc = Integer.parseInt(input.readLine());
             koszty = new int[ilosc][];
             for (int i = 0; i<ilosc; i++)
             {
                koszty[i] = new int[ilosc];
             }

             for(int j = 0; j < ilosc*(ilosc-1); j++)
             {
                 linia = input.readLine();
                 String[] liczby = linia.split(" ");
                 m1 = Integer.parseInt(liczby[0]);
                 m2 = Integer.parseInt(liczby[1]);
                 k = Integer.parseInt(liczby[2]);

                 if (spr_miasta(m1, m2))
                    koszty[m1-1][m2-1] = k;

                 //koszty[m1-1][m2-1] = k;
                 //koszty[m2-1][m1-1] = k;

             }
             for(int i=0; i<ilosc; ++i)
             {
                 koszty[i][i]=INF;
             }
             //doroty
             for(int i=0; i<ilosc; ++i)
             {
                 for(int j=0; j<ilosc; ++j)
                     System.out.print(koszty[i][j]);
                 System.out.println();
             }

        }
        catch (IOException ex){
        }
        /*Costs newCosts = new Costs(ilosc);
        for(int i = 0; i<ilosc; i++)
            for(int j = 0; j<ilosc; j++)
                if (koszty[i][j]!=0)
                    newCosts.setDistances(i, j, koszty[i][j]);
        Solver a = new Solver(newCosts);
        a.branchAndBound();
        Costs root=(Costs)a.tree.getRoot();
        a.createTreeVisualization();
        a.completePath();
        a.printAnswer();*/
        System.out.println("koszty");
        for(int i=0; i<ilosc; ++i)
        {
            for(int j=0; j<ilosc; ++j)
                System.out.print(koszty[i][j]+" ");
            System.out.println();
        }
        Canvas1 kanwa=new Canvas1(ilosc,koszty);
        JFrame frame2=new JFrame("grafDescription");
        frame2.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame2.getContentPane().add(kanwa);
        frame2.pack();
        frame2.setVisible(true);

    this.setVisible(false);    
    }//GEN-LAST:event_jButton1ActionPerformed

 private boolean spr_miasta (int a, int b)
{
    if ((a <= ilosc)&&(b <= ilosc)&&(a != b))
        return true;
    return false;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables

}
